service: peertankis

# Usa el Dockerfile (App Engine Flexible)
runtime: custom
env: flex

env_variables:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "8080"
  PEER_PATH: "/peerjs"
  PEER_PROXIED: "true"
  PEER_ALLOW_DISCOVERY: "false"
  PEER_KEY: "tankis-peer"

# PeerJS suele ser stateful; por seguridad, empieza con 1 instancia.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1


