service: peertankis

# Usa el Dockerfile (App Engine Flexible)
runtime: custom
env: flex

env_variables:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "8080"
  WS_PATH: "/ws"

# WebSocket server es stateful; por seguridad, empieza con 1 instancia.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
