substitutions:
  _REGION: europe-southwest1
  _AR_REPO: peertankis
  _IMAGE: peertankis
  _SERVICE: peertankis

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${COMMIT_SHA}', '.']
    timeout: '1200s'  # Aumentar tiempo de construcción para instalar dependencias

  # Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${COMMIT_SHA}']
    timeout: '600s'  # Aumentar tiempo de subida

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-env-vars"
      - "HOST=0.0.0.0,PEER_PATH=/peerjs,PEER_PROXIED=true,PEER_ALLOW_DISCOVERY=false,PEER_KEY=tankis-peer,ENABLE_TURN=true,TURN_REALM=peertankis-1093381928939.europe-southwest1.run.app,TURN_USER=tankis-turn,TURN_PASSWORD=tankis-turn-secret"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE}:${COMMIT_SHA}"

timeout: "2400s"


